-- 0001 baseline: the live becs-os-core schema as it stood before the revamp (October 2026).
--
-- On the LIVE database these tables already exist, so every statement here is
-- written to do nothing when the object is already there (IF NOT EXISTS,
-- INSERT OR IGNORE). On a fresh database (local dev, tests) it builds the same
-- schema from scratch. Do not edit this file: add a new numbered migration instead.

CREATE TABLE IF NOT EXISTS ventures (id INTEGER PRIMARY KEY AUTOINCREMENT, slug TEXT NOT NULL UNIQUE, name TEXT NOT NULL, description TEXT, status TEXT NOT NULL DEFAULT 'active', created_at TEXT NOT NULL DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS clients (id INTEGER PRIMARY KEY AUTOINCREMENT, venture_id INTEGER REFERENCES ventures(id), name TEXT NOT NULL, contact_name TEXT, email TEXT, phone TEXT, stage TEXT NOT NULL DEFAULT 'lead', source TEXT, notes TEXT, created_at TEXT NOT NULL DEFAULT (datetime('now')), updated_at TEXT NOT NULL DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS projects (id INTEGER PRIMARY KEY AUTOINCREMENT, venture_id INTEGER REFERENCES ventures(id), client_id INTEGER REFERENCES clients(id), name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'planning', priority INTEGER NOT NULL DEFAULT 3, value_cents INTEGER, start_date TEXT, due_date TEXT, notes TEXT, created_at TEXT NOT NULL DEFAULT (datetime('now')), updated_at TEXT NOT NULL DEFAULT (datetime('now')), phase TEXT NOT NULL DEFAULT 'plan');
CREATE TABLE IF NOT EXISTS tasks (id INTEGER PRIMARY KEY AUTOINCREMENT, project_id INTEGER REFERENCES projects(id), venture_id INTEGER REFERENCES ventures(id), title TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'todo', priority INTEGER NOT NULL DEFAULT 3, filter_tag TEXT, due_date TEXT, completed_at TEXT, notes TEXT, created_at TEXT NOT NULL DEFAULT (datetime('now')), updated_at TEXT NOT NULL DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS activity_log (id INTEGER PRIMARY KEY AUTOINCREMENT, entity_type TEXT NOT NULL, entity_id INTEGER NOT NULL, action TEXT NOT NULL, detail TEXT, created_at TEXT NOT NULL DEFAULT (datetime('now')));
CREATE INDEX IF NOT EXISTS idx_clients_stage ON clients(stage);
CREATE INDEX IF NOT EXISTS idx_projects_status ON projects(status);
CREATE INDEX IF NOT EXISTS idx_tasks_status_due ON tasks(status, due_date);
CREATE INDEX IF NOT EXISTS idx_tasks_project ON tasks(project_id);

-- Reserved for the planned Square payment status and client portal. The API does not use them yet.
CREATE TABLE IF NOT EXISTS payments (id INTEGER PRIMARY KEY AUTOINCREMENT, project_id INTEGER NOT NULL REFERENCES projects(id), label TEXT NOT NULL, amount_cents INTEGER NOT NULL DEFAULT 0, status TEXT NOT NULL DEFAULT 'unpaid', due_date TEXT, paid_at TEXT, square_url TEXT, square_invoice_id TEXT, created_at TEXT NOT NULL DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS portal_links (token TEXT PRIMARY KEY, client_id INTEGER NOT NULL UNIQUE REFERENCES clients(id), created_at TEXT NOT NULL DEFAULT (datetime('now')));
CREATE INDEX IF NOT EXISTS idx_payments_project ON payments(project_id);
CREATE INDEX IF NOT EXISTS idx_payments_square ON payments(square_invoice_id);

-- The seven ventures, with fixed ids. Already present live (ignored there).
INSERT OR IGNORE INTO ventures (id, slug, name) VALUES
  (1, 'becs', 'BE Consulting Solutions'),
  (2, 'leaa', 'Lane Ellis Apparel Agency Co.'),
  (3, 'blnks', 'BLNKS'),
  (4, 'me-and-them', 'ME & THEM / M3 & TH3M'),
  (5, '4freq', '4FREQ'),
  (6, 'be-university', 'BE University'),
  (7, 'tethr', 'TETHR');
